[package]
name = "argon2-cloudflare"
version = "0.1.0"
edition = "2021"

# https://github.com/rustwasm/wasm-pack/issues/1247
[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[lib]
crate-type = ["cdylib"]

[dependencies]
argon2 = "0.6.0"
getrandom = { version = "0.4.3", features = ["wasm_js"] }
serde = { version = "1.0.229", features = ["derive"] }
worker = "0.8.5"

[profile.release]
lto = true
# wasm-bindgen needs symbol metadata to generate exception wrappers.
strip = "debuginfo"
codegen-units = 1
